# Generated by Django 5.0.3 on 2024-03-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='student_schedules', through='school_app.Grades', to='school_app.schedules', verbose_name='Занятия'),
        ),
    ]
