# Generated by Django 5.0.3 on 2024-03-13 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField()),
                ('penalties', models.TextField()),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.educator')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Descent'), (2, 'Poor')])),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.student')),
            ],
        ),
    ]
